/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PainelSkillsRouteImport } from './routes/painel.skills'
import { Route as PainelFaturamentoRouteImport } from './routes/painel.faturamento'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelAgenteRouteImport } from './routes/painel.agente'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as PainelSkillsIndexRouteImport } from './routes/painel.skills.index'
import { Route as PainelIntegracoesIndexRouteImport } from './routes/painel.integracoes.index'
import { Route as PainelCronjobsIndexRouteImport } from './routes/painel.cronjobs.index'
import { Route as PainelSkillsPreviewRouteImport } from './routes/painel.skills.preview'
import { Route as PainelSkillsNovaRouteImport } from './routes/painel.skills.nova'
import { Route as PainelSkillsIdRouteImport } from './routes/painel.skills.$id'
import { Route as PainelIntegracoesSlugRouteImport } from './routes/painel.integracoes.$slug'
import { Route as PainelCronjobsNovaRouteImport } from './routes/painel.cronjobs.nova'
import { Route as PainelCronjobsIdRouteImport } from './routes/painel.cronjobs.$id'
import { Route as AdminAgenteIdRouteImport } from './routes/admin.agente.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelSkillsRoute = PainelSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFaturamentoRoute = PainelFaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgenteRoute = PainelAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => PainelRoute,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelSkillsIndexRoute = PainelSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelSkillsRoute,
} as any)
const PainelIntegracoesIndexRoute = PainelIntegracoesIndexRouteImport.update({
  id: '/integracoes/',
  path: '/integracoes/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCronjobsIndexRoute = PainelCronjobsIndexRouteImport.update({
  id: '/cronjobs/',
  path: '/cronjobs/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSkillsPreviewRoute = PainelSkillsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => PainelSkillsRoute,
} as any)
const PainelSkillsNovaRoute = PainelSkillsNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PainelSkillsRoute,
} as any)
const PainelSkillsIdRoute = PainelSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PainelSkillsRoute,
} as any)
const PainelIntegracoesSlugRoute = PainelIntegracoesSlugRouteImport.update({
  id: '/integracoes/$slug',
  path: '/integracoes/$slug',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCronjobsNovaRoute = PainelCronjobsNovaRouteImport.update({
  id: '/cronjobs/nova',
  path: '/cronjobs/nova',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCronjobsIdRoute = PainelCronjobsIdRouteImport.update({
  id: '/cronjobs/$id',
  path: '/cronjobs/$id',
  getParentRoute: () => PainelRoute,
} as any)
const AdminAgenteIdRoute = AdminAgenteIdRouteImport.update({
  id: '/agente/$id',
  path: '/agente/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/painel/agente': typeof PainelAgenteRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/faturamento': typeof PainelFaturamentoRoute
  '/painel/skills': typeof PainelSkillsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/agente/$id': typeof AdminAgenteIdRoute
  '/painel/cronjobs/$id': typeof PainelCronjobsIdRoute
  '/painel/cronjobs/nova': typeof PainelCronjobsNovaRoute
  '/painel/integracoes/$slug': typeof PainelIntegracoesSlugRoute
  '/painel/skills/$id': typeof PainelSkillsIdRoute
  '/painel/skills/nova': typeof PainelSkillsNovaRoute
  '/painel/skills/preview': typeof PainelSkillsPreviewRoute
  '/painel/cronjobs/': typeof PainelCronjobsIndexRoute
  '/painel/integracoes/': typeof PainelIntegracoesIndexRoute
  '/painel/skills/': typeof PainelSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/painel/agente': typeof PainelAgenteRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/faturamento': typeof PainelFaturamentoRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/agente/$id': typeof AdminAgenteIdRoute
  '/painel/cronjobs/$id': typeof PainelCronjobsIdRoute
  '/painel/cronjobs/nova': typeof PainelCronjobsNovaRoute
  '/painel/integracoes/$slug': typeof PainelIntegracoesSlugRoute
  '/painel/skills/$id': typeof PainelSkillsIdRoute
  '/painel/skills/nova': typeof PainelSkillsNovaRoute
  '/painel/skills/preview': typeof PainelSkillsPreviewRoute
  '/painel/cronjobs': typeof PainelCronjobsIndexRoute
  '/painel/integracoes': typeof PainelIntegracoesIndexRoute
  '/painel/skills': typeof PainelSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/painel/agente': typeof PainelAgenteRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/faturamento': typeof PainelFaturamentoRoute
  '/painel/skills': typeof PainelSkillsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/agente/$id': typeof AdminAgenteIdRoute
  '/painel/cronjobs/$id': typeof PainelCronjobsIdRoute
  '/painel/cronjobs/nova': typeof PainelCronjobsNovaRoute
  '/painel/integracoes/$slug': typeof PainelIntegracoesSlugRoute
  '/painel/skills/$id': typeof PainelSkillsIdRoute
  '/painel/skills/nova': typeof PainelSkillsNovaRoute
  '/painel/skills/preview': typeof PainelSkillsPreviewRoute
  '/painel/cronjobs/': typeof PainelCronjobsIndexRoute
  '/painel/integracoes/': typeof PainelIntegracoesIndexRoute
  '/painel/skills/': typeof PainelSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bem-vindo'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/reembolso'
    | '/signup'
    | '/termos'
    | '/checkout/sucesso'
    | '/painel/agente'
    | '/painel/configuracoes'
    | '/painel/faturamento'
    | '/painel/skills'
    | '/admin/'
    | '/painel/'
    | '/admin/agente/$id'
    | '/painel/cronjobs/$id'
    | '/painel/cronjobs/nova'
    | '/painel/integracoes/$slug'
    | '/painel/skills/$id'
    | '/painel/skills/nova'
    | '/painel/skills/preview'
    | '/painel/cronjobs/'
    | '/painel/integracoes/'
    | '/painel/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/reembolso'
    | '/signup'
    | '/termos'
    | '/checkout/sucesso'
    | '/painel/agente'
    | '/painel/configuracoes'
    | '/painel/faturamento'
    | '/admin'
    | '/painel'
    | '/admin/agente/$id'
    | '/painel/cronjobs/$id'
    | '/painel/cronjobs/nova'
    | '/painel/integracoes/$slug'
    | '/painel/skills/$id'
    | '/painel/skills/nova'
    | '/painel/skills/preview'
    | '/painel/cronjobs'
    | '/painel/integracoes'
    | '/painel/skills'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bem-vindo'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/reembolso'
    | '/signup'
    | '/termos'
    | '/checkout/sucesso'
    | '/painel/agente'
    | '/painel/configuracoes'
    | '/painel/faturamento'
    | '/painel/skills'
    | '/admin/'
    | '/painel/'
    | '/admin/agente/$id'
    | '/painel/cronjobs/$id'
    | '/painel/cronjobs/nova'
    | '/painel/integracoes/$slug'
    | '/painel/skills/$id'
    | '/painel/skills/nova'
    | '/painel/skills/preview'
    | '/painel/cronjobs/'
    | '/painel/integracoes/'
    | '/painel/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BemVindoRoute: typeof BemVindoRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/skills': {
      id: '/painel/skills'
      path: '/skills'
      fullPath: '/painel/skills'
      preLoaderRoute: typeof PainelSkillsRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/faturamento': {
      id: '/painel/faturamento'
      path: '/faturamento'
      fullPath: '/painel/faturamento'
      preLoaderRoute: typeof PainelFaturamentoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agente': {
      id: '/painel/agente'
      path: '/agente'
      fullPath: '/painel/agente'
      preLoaderRoute: typeof PainelAgenteRouteImport
      parentRoute: typeof PainelRoute
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/skills/': {
      id: '/painel/skills/'
      path: '/'
      fullPath: '/painel/skills/'
      preLoaderRoute: typeof PainelSkillsIndexRouteImport
      parentRoute: typeof PainelSkillsRoute
    }
    '/painel/integracoes/': {
      id: '/painel/integracoes/'
      path: '/integracoes'
      fullPath: '/painel/integracoes/'
      preLoaderRoute: typeof PainelIntegracoesIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cronjobs/': {
      id: '/painel/cronjobs/'
      path: '/cronjobs'
      fullPath: '/painel/cronjobs/'
      preLoaderRoute: typeof PainelCronjobsIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/skills/preview': {
      id: '/painel/skills/preview'
      path: '/preview'
      fullPath: '/painel/skills/preview'
      preLoaderRoute: typeof PainelSkillsPreviewRouteImport
      parentRoute: typeof PainelSkillsRoute
    }
    '/painel/skills/nova': {
      id: '/painel/skills/nova'
      path: '/nova'
      fullPath: '/painel/skills/nova'
      preLoaderRoute: typeof PainelSkillsNovaRouteImport
      parentRoute: typeof PainelSkillsRoute
    }
    '/painel/skills/$id': {
      id: '/painel/skills/$id'
      path: '/$id'
      fullPath: '/painel/skills/$id'
      preLoaderRoute: typeof PainelSkillsIdRouteImport
      parentRoute: typeof PainelSkillsRoute
    }
    '/painel/integracoes/$slug': {
      id: '/painel/integracoes/$slug'
      path: '/integracoes/$slug'
      fullPath: '/painel/integracoes/$slug'
      preLoaderRoute: typeof PainelIntegracoesSlugRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cronjobs/nova': {
      id: '/painel/cronjobs/nova'
      path: '/cronjobs/nova'
      fullPath: '/painel/cronjobs/nova'
      preLoaderRoute: typeof PainelCronjobsNovaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cronjobs/$id': {
      id: '/painel/cronjobs/$id'
      path: '/cronjobs/$id'
      fullPath: '/painel/cronjobs/$id'
      preLoaderRoute: typeof PainelCronjobsIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/agente/$id': {
      id: '/admin/agente/$id'
      path: '/agente/$id'
      fullPath: '/admin/agente/$id'
      preLoaderRoute: typeof AdminAgenteIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgenteIdRoute: typeof AdminAgenteIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAgenteIdRoute: AdminAgenteIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PainelSkillsRouteChildren {
  PainelSkillsIdRoute: typeof PainelSkillsIdRoute
  PainelSkillsNovaRoute: typeof PainelSkillsNovaRoute
  PainelSkillsPreviewRoute: typeof PainelSkillsPreviewRoute
  PainelSkillsIndexRoute: typeof PainelSkillsIndexRoute
}

const PainelSkillsRouteChildren: PainelSkillsRouteChildren = {
  PainelSkillsIdRoute: PainelSkillsIdRoute,
  PainelSkillsNovaRoute: PainelSkillsNovaRoute,
  PainelSkillsPreviewRoute: PainelSkillsPreviewRoute,
  PainelSkillsIndexRoute: PainelSkillsIndexRoute,
}

const PainelSkillsRouteWithChildren = PainelSkillsRoute._addFileChildren(
  PainelSkillsRouteChildren,
)

interface PainelRouteChildren {
  PainelAgenteRoute: typeof PainelAgenteRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelFaturamentoRoute: typeof PainelFaturamentoRoute
  PainelSkillsRoute: typeof PainelSkillsRouteWithChildren
  PainelIndexRoute: typeof PainelIndexRoute
  PainelCronjobsIdRoute: typeof PainelCronjobsIdRoute
  PainelCronjobsNovaRoute: typeof PainelCronjobsNovaRoute
  PainelIntegracoesSlugRoute: typeof PainelIntegracoesSlugRoute
  PainelCronjobsIndexRoute: typeof PainelCronjobsIndexRoute
  PainelIntegracoesIndexRoute: typeof PainelIntegracoesIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgenteRoute: PainelAgenteRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelFaturamentoRoute: PainelFaturamentoRoute,
  PainelSkillsRoute: PainelSkillsRouteWithChildren,
  PainelIndexRoute: PainelIndexRoute,
  PainelCronjobsIdRoute: PainelCronjobsIdRoute,
  PainelCronjobsNovaRoute: PainelCronjobsNovaRoute,
  PainelIntegracoesSlugRoute: PainelIntegracoesSlugRoute,
  PainelCronjobsIndexRoute: PainelCronjobsIndexRoute,
  PainelIntegracoesIndexRoute: PainelIntegracoesIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BemVindoRoute: BemVindoRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ReembolsoRoute: ReembolsoRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
